version: 1.0.{build}
image: Ubuntu2204
stack: node 21
branches:
  only:
    - master

cache:
  - node_modules

install:
  - npm install

build:
  project: npm run build

deploy:
  - provider: GitHub
    repository: anassstya/games
    branch: gh-pages
    token: %GITHUB_TOKEN%
    local_dir: dist
    on:
      branch: master
