# appveyor.yml
image: Ubuntu2204
stack: node 21
branches:
  only:
    - master
cache: node_modules

install:
  - npm install

build_script:
  - npm run build

artifacts:
  - path: dist
    name: "GitHub Pages"

deploy:
  provider: GitHub
  token: %GITHUB_TOKEN% 
  on:
    branch: master
  artifact: dist
