image: Ubuntu2204
stack: node 21
branches:
  only:
    - master

cache:
  - node_modules

install:
  - npm install

build:
  off

deploy:
  - provider: GitHub
    repository: anassstya/games
    branch: gh-pages
    token: %GITHUB_TOKEN%
    on:
      branch: master
